---
name: Python Static Checks

on:
  push:
    paths:
      - '**.py'

jobs:
  python-static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Run Static Checks
        run: |
          ruff format --check .
          ruff check .
          mypy --pretty .
